### ISSUE TITLE
Integrity Test Tool (part 2) for Schema + Data

### ISSUE THREAD

**Issue by flyingsilverfin** [vaticle/typedb-behaviour#16]
The Integrity tool currently only builds and tests the sets required for analysing the schema integrity following the formal semantics. We should extend this tool to also validate all the data, and update it to match the expected Semantics for the target release of Grakn (currently Grakn 2.0)

**Comment by alexjpwalker** [comment]
@flyingsilverfin Should we close this as invalid, or change it to be "Integrity Test Tool"?

**Comment by flyingsilverfin** [comment]
let's close it, we're not planning on building this feature.
